import test from 'node:test';import assert from 'node:assert/strict';
import {canonical,sha256,appendEvent,auditMatch,summarize,csv,statistics,distributionMetrics} from '../public/analytics.js';
import {createInitialState,applyAction,serialize,getOutcome} from '../public/games/dots-and-boxes/rules.js';
async function fixture(){const m={id:'fixture',state:createInitialState({size:1}),events:[],mode:'local',ranked:false,verified:false,status:'active',createdAt:Date.now()};for(const edgeId of [0,1,2,3]){const before=m.state,decisionId=`d${edgeId}`,player=before.toMove;if(player===1)await appendEvent(m,'decision_completed',{decisionId,edgeId,source:'local',candidateCount:4-edgeId,totalMs:10,confidence:null});const transition=applyAction(before,{edgeId});m.state=transition.state;await appendEvent(m,'move_committed',{...transition.event,decisionId,source:player===1?'local':'human',preStateHash:await sha256(serialize(before)),postStateHash:await sha256(serialize(m.state)),turnElapsedMs:5});}m.status='completed';m.outcome=getOutcome(m.state);return m;}
test('canonical JSON sorts keys and stable hashes agree',async()=>{assert.equal(canonical({b:1,a:2}),'{"a":2,"b":1}');assert.equal(await sha256({b:1,a:2}),await sha256({a:2,b:1}));});
test('valid journal passes structural and gameplay audit',async()=>{const m=await fixture(),r=await auditMatch(m);assert.equal(r.ok,true,JSON.stringify(r.errors));assert.equal(r.score.human+r.score.jev,1);});
for(const [name,tamper] of [['modified data',m=>m.events[0].data.edgeId=2],['deleted event',m=>m.events.splice(1,1)],['reordered events',m=>m.events.reverse()],['forged outcome',m=>m.outcome='draw'],['forged final board',m=>m.state.edges[0]=1]])test(`audit rejects ${name}`,async()=>{const m=await fixture();tamper(m);assert.equal((await auditMatch(m)).ok,false);});
test('summary distinguishes sources, null probabilities and unknown costs',async()=>{const s=summarize(await fixture());assert.equal(s.moveCount,4);assert.equal(s.sources.local,2);assert.equal(s.estimatedCostUsd,null);assert.equal(s.providerAttempts,0);assert.equal(s.confidence.mean,null);});
test('quantiles and entropy are computed from measured data',()=>{assert.equal(statistics([1,2,3,4]).p50,2.5);assert.equal(statistics([null]).n,0);assert.equal(distributionMetrics({a:.5,b:.5}).entropyBits,1);assert.equal(distributionMetrics({a:1,b:0}).normalizedEntropy,0);});
test('CSV escapes quotes and neutralizes spreadsheet formula injection',()=>{const text=csv([{name:'=HYPERLINK("bad")',value:3,negative:-2}]);assert.ok(text.includes("'=HYPERLINK"));assert.ok(text.includes('"-2"'));assert.equal(csv([]),'');});
