import test from 'node:test';import assert from 'node:assert/strict';
import {environment,Client,mockProvider} from './helpers.mjs';
import {getLegalActions} from '../public/games/dots-and-boxes/rules.js';
import {sha256,auditMatch} from '../public/analytics.js';
import {poolId} from '../src/matches.js';
import {issueSession} from '../src/auth.js';

test('guest bootstrap, authoritative game, complete replay, CSV and verification',async()=>{const env=environment(),c=new Client(env);try{
  const boot=await c.init();assert.equal(boot.status,200);assert.equal(boot.body.user,null);assert.ok(c.cookie);assert.ok(c.csrf);
  let result=await c.create(),m=result.body;assert.equal(result.status,201,JSON.stringify(m));
  while(m.status==='active'){
    result=await c.step(m,m.state.toMove===0?'human_move':'jev_advance',m.state.toMove===0?getLegalActions(m.state)[0].edgeId:undefined);
    assert.equal(result.status,200,JSON.stringify(result.body));m=result.body;
  }
  assert.equal(m.state.ply,40);assert.equal(m.summary.score.human+m.summary.score.jev,16);assert.equal(m.verified,true);assert.equal(m.ranked,false);
  const audit=await c.request(`/api/matches/${m.id}/export?format=audit`);assert.equal(audit.body.ok,true,JSON.stringify(audit.body.errors));
  const exported=await c.request(`/api/matches/${m.id}/export?format=json`);assert.equal((await auditMatch(exported.body)).ok,true);assert.equal(JSON.stringify(exported.body).includes(env.TYPESAFE_API_KEY),false);
  const csv=await c.request(`/api/matches/${m.id}/export?format=moves`);assert.equal(csv.status,200);assert.ok(csv.headers.get('content-type').includes('text/csv'));
}finally{env.DB.close();}});
test('origin, CSRF and invalid JSON are rejected',async()=>{const env=environment(),c=new Client(env);try{await c.init();assert.equal((await c.request('/api/matches',{method:'POST',data:{},headers:{origin:'https://attacker.invalid'}})).status,403);assert.equal((await c.request('/api/matches',{method:'POST',data:{},headers:{'x-csrf-token':'bad'}})).status,403);assert.equal((await c.create({ranked:'false'})).status,400);}finally{env.DB.close();}});
test('ranked requires authenticated Discord and the actual JEV mode',async()=>{const env=environment(),c=new Client(env);try{await c.init();assert.equal((await c.create({ranked:true,mode:'jev'})).status,401);await c.user();assert.equal((await c.create({ranked:true,mode:'local'})).status,400);const valid=await c.create({ranked:true,mode:'jev'});assert.equal(valid.status,201);assert.equal(valid.body.state.firstPlayer,0);assert.equal(valid.body.ranked,true);}finally{env.DB.close();}});
test('only owner may read, act, export or retrieve event evidence',async()=>{const env=environment(),a=new Client(env),b=new Client(env);try{await a.init();await b.init();const {body:m}=await a.create();for(const suffix of ['', '/events','/export?format=json'])assert.equal((await b.request(`/api/matches/${m.id}${suffix}`)).status,404);assert.equal((await b.step(m,'human_move',0)).status,404);}finally{env.DB.close();}});
test('illegal and stale actions do not mutate state; duplicate requests are idempotent',async()=>{const env=environment(),c=new Client(env);try{await c.init();let {body:m}=await c.create();const id=crypto.randomUUID();const first=await c.step(m,'human_move',0,id);assert.equal(first.status,200);assert.equal(first.body.revision,1);const duplicate=await c.step(m,'human_move',0,id);assert.equal(duplicate.status,200);assert.equal(duplicate.body.revision,1);assert.equal((await c.step(m,'human_move',1,id)).status,409);assert.equal((await c.step(m,'human_move',2)).status,409);assert.equal((await c.step(first.body,'human_move',2)).status,409);assert.equal((await c.create()).status,409);}finally{env.DB.close();}});
test('concurrent opponent requests cannot commit two moves or choose a rerolled response',async()=>{let calls=0;const env=environment({FETCH:async(url,init)=>{calls++;await new Promise(r=>setTimeout(r,30));return mockProvider(url,init);}}),c=new Client(env);try{await c.init();let {body:m}=await c.create({mode:'jev'});m=(await c.step(m,'human_move',0)).body;const replies=await Promise.all([c.step(m,'jev_advance'),c.step(m,'jev_advance')]);assert.ok(replies.some(r=>r.status===200));assert.ok(replies.every(r=>[200,202,409].includes(r.status)));assert.equal(calls,1);assert.equal((await c.request(`/api/matches/${m.id}`)).body.revision,2);}finally{env.DB.close();}});
test('provider failure explicitly demotes ranked match and records the failure',async()=>{const env=environment({FETCH:async()=>new Response('',{status:401})}),c=new Client(env);try{await c.user();let {body:m}=await c.create({mode:'jev',ranked:true});m=(await c.step(m,'human_move',0)).body;const next=await c.step(m,'jev_advance');assert.equal(next.status,200);assert.equal(next.body.ranked,false);assert.equal(next.body.mode,'local');assert.match(next.body.notice,/not ranked/);const e=(await c.request(`/api/matches/${m.id}/events`)).body.events;assert.ok(e.some(e=>e.type==='provider_attempt'&&e.data.errorCode==='http_401'));assert.ok(e.some(e=>e.type==='ranked_eligibility_voided'));}finally{env.DB.close();}});
test('ranked seats alternate across concessions',async()=>{const env=environment(),c=new Client(env);try{await c.user();const {body:a}=await c.create({mode:'jev',ranked:true});assert.equal(a.state.firstPlayer,0);assert.equal((await c.step(a,'resign')).status,200);const {body:b}=await c.create({mode:'jev',ranked:true});assert.equal(b.state.firstPlayer,1);}finally{env.DB.close();}});
test('a reused launch cannot create another community match; arbitrary IDs are ignored',async()=>{const env=environment(),c=new Client(env);try{const s=await c.user(),raw='a'.repeat(64),hash=await sha256(raw);await env.DB.prepare('INSERT INTO discord_launches VALUES(?,?,?,?,?,?)').bind(hash,'111111','123456789012345678','222222','333333',Date.now()+600000).run();assert.equal((await c.request('/api/session/context',{method:'POST',data:{launch:raw}})).status,200);const {body:m}=await c.create({guild_id:'666666',channel_id:'777777'});const row=await env.DB.prepare('SELECT guild_id,channel_id FROM matches WHERE id=?').bind(m.id).first();assert.equal(row.guild_id,'222222');assert.equal(row.channel_id,'333333');await c.step(m,'resign');await c.request('/api/session/context',{method:'POST',data:{launch:raw}});assert.equal((await c.create()).status,409);}finally{env.DB.close();}});
test('launch binding rejects other users and expiration',async()=>{const env=environment(),c=new Client(env);try{await c.user();const raw='b'.repeat(64);await env.DB.prepare('INSERT INTO discord_launches VALUES(?,?,?,?,?,?)').bind(await sha256(raw),'444444','999999','222222','333333',Date.now()+100000).run();assert.equal((await c.request('/api/session/context',{method:'POST',data:{launch:raw}})).status,403);}finally{env.DB.close();}});
test('client telemetry requires consent and accepts only enumerated fields',async()=>{const env=environment(),c=new Client(env);try{await c.init();const {body:m}=await c.create();const path=`/api/matches/${m.id}/telemetry`;assert.equal((await c.request(path,{method:'POST',data:{events:[]}})).status,400);assert.equal((await c.request(path,{method:'POST',data:{consent:true,events:[{type:'arbitrary_text',text:'secret'}]}})).status,400);assert.equal((await c.request(path,{method:'POST',data:{consent:true,events:[{type:'render_sample',durationMs:12,text:'not retained'}]}})).status,200);const logs=await env.DB.prepare("SELECT data_json FROM operational_events WHERE type='client_telemetry'").all();assert.equal(JSON.stringify(logs).includes('not retained'),false);}finally{env.DB.close();}});
test('security headers and logs never include cookies or secret-bearing query strings',async()=>{const env=environment(),c=new Client(env);try{const res=await c.init();assert.ok(res.headers.get('content-security-policy').includes("script-src 'self'"));await c.request('/api/missing?launch=SHOULD_NOT_LOG');const logs=await env.DB.prepare('SELECT data_json FROM operational_events').all();assert.equal(JSON.stringify(logs).includes('SHOULD_NOT_LOG'),false);assert.equal(JSON.stringify(logs).includes(c.cookie),false);}finally{env.DB.close();}});
async function seedBoard(env,id,name,{guild='222222',channel='333333',wins=20,pool=null}={}){
  await env.DB.prepare('INSERT INTO users VALUES(?,?,?,?,?)').bind(id,name,null,Date.now(),Date.now()).run();pool??=await poolId(env,'easy');
  for(let i=0;i<20;i++)await env.DB.prepare('INSERT INTO matches(id,owner_key,user_id,guild_id,channel_id,pool_id,season_id,attempt_no,first_player,status,ranked,verified,outcome,created_at,expires_at,version,record_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),`user:${id}`,id,guild,channel,pool,new Date().toISOString().slice(0,7),i,i%2,'completed',1,1,i<wins?'win':'loss',Date.now(),Date.now()+1000,0,'{}').run();
}
test('leaderboard pools and channel/server scopes remain isolated; ties share rank',async()=>{const env=environment(),c=new Client(env);try{
  await seedBoard(env,'111111','A');await seedBoard(env,'222222','B');await seedBoard(env,'333333','C',{guild:'555555',channel:'666666',wins:18});await seedBoard(env,'444444','Wrong pool',{pool:'different'});
  let res=await c.request('/api/leaderboard?difficulty=easy&period=all');assert.equal(res.status,200,JSON.stringify(res.body));assert.equal(res.body.rows.length,3);assert.deepEqual(res.body.rows.map(r=>r.rank),[1,1,2]);assert.equal(JSON.stringify(res.body).includes('333333'),false);
  assert.equal((await c.request('/api/leaderboard?difficulty=easy&scope=channel')).status,403);
  const s=await c.user('777777');await env.DB.prepare('UPDATE sessions SET context_json=? WHERE token_hash=?').bind(JSON.stringify({guildId:'222222',channelId:'333333',expiresAt:Date.now()+10000}),s.token_hash).run();
  res=await c.request('/api/leaderboard?difficulty=easy&scope=channel');assert.equal(res.body.rows.length,2);res=await c.request('/api/leaderboard?difficulty=easy&scope=server');assert.equal(res.body.rows.length,2);
}finally{env.DB.close();}});
test('keyset pagination preserves score ties across pages',async()=>{const env=environment(),c=new Client(env);try{for(let i=0;i<27;i++)await seedBoard(env,String(100000+i),'Player '+i);const first=await c.request('/api/leaderboard?difficulty=easy');assert.equal(first.body.rows.length,25);assert.ok(first.body.nextCursor);const second=await c.request('/api/leaderboard?difficulty=easy&cursor='+encodeURIComponent(first.body.nextCursor));assert.equal(second.body.rows.length,2);assert.equal(second.body.nextCursor,null);assert.equal(first.body.rows[0].rank,1);assert.equal(second.body.rows[0].rank,1);assert.equal((await c.request('/api/leaderboard?difficulty=hard&cursor='+encodeURIComponent(first.body.nextCursor))).status,400);}finally{env.DB.close();}});

test('complete mocked JEV ranked match retains auditable provider evidence',async()=>{const env=environment(),c=new Client(env);try{await c.user();let {body:m}=await c.create({mode:'jev',ranked:true});while(m.status==='active'){const result=await c.step(m,m.state.toMove===0?'human_move':'jev_advance',m.state.toMove===0?getLegalActions(m.state)[0].edgeId:undefined);assert.equal(result.status,200,JSON.stringify(result.body));m=result.body;}assert.equal(m.verified,true);assert.equal(m.ranked,true);const full=(await c.request(`/api/matches/${m.id}/export?format=json`)).body;const audit=await auditMatch(full);assert.equal(audit.ok,true,JSON.stringify(audit.errors));assert.ok(full.events.some(e=>e.type==='provider_attempt'));assert.ok(full.events.every(e=>e.clock?.domainId&&Number.isFinite(e.clock.monotonicMs)));}finally{env.DB.close();}});
test('source revision change cannot silently alter an existing opponent profile',async()=>{const env=environment({SOURCE_REVISION:'revision-A'}),c=new Client(env);try{await c.user();let {body:m}=await c.create({mode:'jev',ranked:true});m=(await c.step(m,'human_move',0)).body;env.SOURCE_REVISION='revision-B';const result=await c.step(m,'jev_advance');assert.equal(result.status,409);assert.equal((await c.request(`/api/matches/${m.id}`)).body.state.ply,1);}finally{env.DB.close();}});
