import test from 'node:test';import assert from 'node:assert/strict';
import {environment,Client} from './helpers.mjs';import {verifyDiscordSignature,interaction} from '../src/discord.js';import {sha256} from '../public/analytics.js';
const hex=b=>Buffer.from(b).toString('hex');
test('Ed25519 signed interaction verifies raw body, freshness and signature',async()=>{const keys=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']),publicKey=hex(await crypto.subtle.exportKey('raw',keys.publicKey)),text='{"type":1}',stamp=String(Math.floor(Date.now()/1000)),signature=hex(await crypto.subtle.sign('Ed25519',keys.privateKey,new TextEncoder().encode(stamp+text))),r=new Request('http://localhost',{headers:{'x-signature-timestamp':stamp,'x-signature-ed25519':signature}});assert.equal(await verifyDiscordSignature(r,text,publicKey),true);assert.equal(await verifyDiscordSignature(r,text+' ',publicKey),false);assert.equal(await verifyDiscordSignature(r,text,publicKey,Date.now()+600000),false);});
test('OAuth requests only identify and binds one-time state to the browser session',async()=>{const env=environment({DISCORD_CLIENT_ID:'111111',DISCORD_CLIENT_SECRET:'secret'}),a=new Client(env),b=new Client(env);try{await a.init();await b.init();const started=await a.request('/api/auth/discord');assert.equal(started.status,302);const location=new URL(started.headers.get('location'));assert.equal(location.searchParams.get('scope'),'identify');const state=location.searchParams.get('state');assert.equal((await b.request(`/api/auth/discord/callback?state=${state}&code=test`)).status,403);const cancelled=await a.request(`/api/auth/discord/callback?state=${state}&error=access_denied`);assert.equal(cancelled.status,302);assert.equal((await a.request(`/api/auth/discord/callback?state=${state}&error=access_denied`)).status,403);}finally{env.DB.close();}});
test('OAuth success rotates cookie and never retains provider tokens',async()=>{let calls=0;const env=environment({DISCORD_CLIENT_ID:'111111',DISCORD_CLIENT_SECRET:'secret',FETCH:async()=>new Response(JSON.stringify(++calls===1?{access_token:'SHOULD_NEVER_BE_STORED',refresh_token:'ALSO_SECRET'}:{id:'123456789012345678',username:'test',global_name:'Display Test',avatar:null}),{headers:{'Content-Type':'application/json'}})}),c=new Client(env);try{await c.init();const old=c.cookie,started=await c.request('/api/auth/discord'),state=new URL(started.headers.get('location')).searchParams.get('state');const result=await c.request(`/api/auth/discord/callback?state=${state}&code=one-time-code`);assert.equal(result.status,302,JSON.stringify(result.body));assert.notEqual(c.cookie,old);const current=await c.init();assert.equal(current.body.user.display_name,'Display Test');const sessions=await env.DB.prepare('SELECT * FROM sessions').all();assert.equal(sessions.results.length,1);assert.equal(JSON.stringify(sessions).includes('SHOULD_NEVER'),false);}finally{env.DB.close();}});
test('expired session cannot mutate matches',async()=>{const env=environment(),c=new Client(env);try{await c.init();await env.DB.prepare('UPDATE sessions SET expires_at=0').run();assert.equal((await c.create()).status,401);}finally{env.DB.close();}});
test('logout revokes the server session',async()=>{const env=environment(),c=new Client(env);try{await c.init();const old=c.cookie;assert.equal((await c.request('/api/logout',{method:'POST',data:{}})).status,200);c.cookie=old;assert.equal((await c.create()).status,401);}finally{env.DB.close();}});
test('full signed Discord command issues opaque, user-bound launch and rejects duplicate',async()=>{const keys=await crypto.subtle.generateKey({name:'Ed25519'},true,['sign','verify']),publicKey=hex(await crypto.subtle.exportKey('raw',keys.publicKey)),env=environment({DISCORD_CLIENT_ID:'111111',DISCORD_PUBLIC_KEY:publicKey});try{
  const payload={id:'555555',application_id:'111111',type:2,data:{name:'play'},guild_id:'222222',channel:{id:'333333',type:0},member:{user:{id:'444444'}}},text=JSON.stringify(payload),stamp=String(Math.floor(Date.now()/1000)),sig=hex(await crypto.subtle.sign('Ed25519',keys.privateKey,new TextEncoder().encode(stamp+text)));
  const make=()=>new Request(env.APP_ORIGIN+'/api/discord/interactions',{method:'POST',headers:{'x-signature-timestamp':stamp,'x-signature-ed25519':sig},body:text});
  const response=await interaction(make(),env),value=await response.json();assert.equal(value.data.flags,64);const launch=new URL(value.data.components[0].components[0].url).searchParams.get('launch'),row=await env.DB.prepare('SELECT * FROM discord_launches WHERE token_hash=?').bind(await sha256(launch)).first();assert.equal(row.discord_user_id,'444444');assert.equal(row.channel_id,'333333');const duplicate=await interaction(make(),env);assert.match((await duplicate.json()).data.content,/already handled/);
}finally{env.DB.close();}});
