import test from 'node:test';import assert from 'node:assert/strict';
import {prepareDecision,evaluatePrepared,validateProviderResponse} from '../src/jev.js';
import {createInitialState,applyAction} from '../public/games/dots-and-boxes/rules.js';
import {mockProvider} from './helpers.mjs';
const model='jev-1.13.0';
function response(){return {model,answers:{move:{type:'choice',choice:'1',confidence:.2,probabilities:{'0':.5,'1':.5}}},usage:{input_tokens:1,output_tokens:2}};}
test('accept documented contract and deterministically resolve tied options',()=>{const parsed=validateProviderResponse(response(),[0,1],model);assert.equal(parsed.edgeId,0);assert.equal(parsed.confidence,.2);});
for(const [name,modify] of [
 ['wrong model',r=>r.model='jev-latest'],['illegal choice',r=>r.answers.move.choice='99'],['missing key',r=>delete r.answers.move.probabilities['0']],
 ['extra key',r=>r.answers.move.probabilities['2']=0],['bad sum',r=>r.answers.move.probabilities['0']=.1],['negative probability',r=>r.answers.move.probabilities['0']=-.5],
 ['NaN confidence',r=>r.answers.move.confidence=NaN],['wrong type',r=>r.answers.move.type='noul'],['choice is not argmax',r=>{r.answers.move.probabilities={'0':.9,'1':.1};}]
])test(`reject ${name}`,()=>{const r=response();modify(r);assert.throws(()=>validateProviderResponse(r,[0,1],model));});
test('real request structure contains every legal edge and no browser/user context',async()=>{const p=await prepareDecision(createInitialState(),'easy',model);assert.equal(Object.keys(p.request.questions.move.criteria).length,40);assert.equal(p.request.questions.move.type,'choice');assert.equal(JSON.stringify(p.request).includes('discord'),false);assert.equal(p.requestHash.length,64);});
test('successful provider call records usage, cost and returned probability evidence',async()=>{const s=createInitialState(),p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{TYPESAFE_API_KEY:'test',FETCH:mockProvider,INPUT_USD_PER_MILLION:'1',OUTPUT_USD_PER_MILLION:'2'});assert.equal(d.source,'jev');assert.equal(d.attempts.length,1);assert.equal(d.attempts[0].usage.input_tokens,120);assert.equal(d.attempts[0].estimatedCostUsd,.00018);assert.ok(d.response.answers.move);});
test('no key is an explicitly identified fallback and unknown costs are null',async()=>{const s=createInitialState(),p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{});assert.equal(d.source,'fallback');assert.equal(d.failure,'not_configured');assert.equal(d.confidence,null);});
test('local mode never calls the provider or pretends to be JEV',async()=>{const s=createInitialState(),p=await prepareDecision(s,'easy',model);const d=await evaluatePrepared(p,s,'local',{FETCH:()=>{throw Error('must not call');}});assert.equal(d.source,'local');assert.equal(d.attempts.length,0);});
test('transient HTTP failure gets one bounded retry and complete attempt accounting',async()=>{let count=0;const s=createInitialState(),p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{TYPESAFE_API_KEY:'test',FETCH:async(url,init)=>++count===1?new Response('',{status:529}):mockProvider(url,init)});assert.equal(d.source,'jev');assert.equal(count,2);assert.equal(d.attempts[0].errorCode,'http_529');assert.equal(d.attempts[1].ok,true);});
test('a long Retry-After is respected without an early retry',async()=>{let count=0;const s=createInitialState(),p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{TYPESAFE_API_KEY:'test',FETCH:async()=>{count++;return new Response('',{status:429,headers:{'retry-after':'30'}});}});assert.equal(count,1);assert.equal(d.source,'fallback');});
test('malformed response is not repeatedly sampled',async()=>{let count=0;const s=createInitialState(),p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{TYPESAFE_API_KEY:'test',FETCH:async()=>{count++;return new Response('{}');}});assert.equal(count,1);assert.equal(d.source,'fallback');});
test('timeout produces at most two attempts',async()=>{const s=createInitialState(),p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{TYPESAFE_API_KEY:'test',JEV_TIMEOUT_MS:'5',FETCH:async(_u,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))))});assert.equal(d.attempts.length,2);assert.equal(d.failure,'timeout');});
test('only one legal move bypasses API with a forced source',async()=>{let s=createInitialState({size:1});for(const edgeId of [0,1,2])s=applyAction(s,{edgeId}).state;const p=await prepareDecision(s,'easy',model),d=await evaluatePrepared(p,s,'jev',{FETCH:()=>{throw Error();}});assert.equal(d.source,'forced');assert.equal(d.edgeId,3);});
