import test from 'node:test';import assert from 'node:assert/strict';
import {geometry,createInitialState,getLegalActions,applyAction,serialize,deserialize,getScore,getOutcome,replay,RULES_VERSION} from '../public/games/dots-and-boxes/rules.js';
import {analyzeCandidates,components,exactRegret,heuristicAction} from '../public/games/dots-and-boxes/analysis.js';
function rng(seed){return()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};}
test('4x4 default has 40 edges, 16 boxes and correct adjacency',()=>{const s=createInitialState(),g=geometry();assert.equal(s.edges.length,40);assert.equal(s.boxes.length,16);assert.equal(getLegalActions(s).length,40);assert.equal(g.edges.filter(e=>e.boxes.length===1).length,16);assert.equal(g.edges.filter(e=>e.boxes.length===2).length,24);});
test('all supported sizes have unique geometry and round-trip serialization',()=>{for(let size=1;size<=6;size++){const g=geometry(size),s=createInitialState({size});assert.equal(new Set(g.edges.map(e=>e.id)).size,2*size*(size+1));assert.deepEqual(deserialize(serialize(s)),s);for(const b of g.boxes)for(const e of b.edges)assert.ok(g.edges[e].boxes.includes(b.id));}});
test('two boxes award two points but only one edge and retained turn',()=>{let s=createInitialState({size:2});for(const edgeId of [0,1,2,3,6,8])s=applyAction(s,{edgeId}).state;const actor=s.toMove,{state,event}=applyAction(s,{edgeId:7});assert.deepEqual(event.capturedBoxes,[0,1]);assert.equal(state.toMove,actor);assert.equal(state.ply,7);assert.equal(state.boxes.filter(b=>b===actor).length,2);});
test('illegal moves rejected without mutation',()=>{const s=createInitialState(),original=serialize(s);for(const edgeId of [-1,40,1.5,'0',null,undefined,NaN])assert.throws(()=>applyAction(s,{edgeId}));assert.equal(serialize(s),original);const next=applyAction(s,{edgeId:0}).state;assert.throws(()=>applyAction(next,{edgeId:0}));assert.equal(serialize(s),original);});
test('capturing an available box is optional',()=>{let s=createInitialState({size:2});for(const edgeId of [0,2,6])s=applyAction(s,{edgeId}).state;assert.ok(getLegalActions(s).some(a=>a.edgeId===7));const transition=applyAction(s,{edgeId:1});assert.equal(transition.event.capturedBoxes.length,0);assert.equal(transition.state.toMove,1-s.toMove);});
test('exhaustively enumerate all 1x1 edge orders and both starters',()=>{let leaves=0;function visit(s){if(s.toMove===null){assert.equal(getScore(s).human+getScore(s).jev,1);assert.notEqual(getOutcome(s),'draw');assert.throws(()=>applyAction(s,{edgeId:0}));leaves++;return;}for(const a of getLegalActions(s)){const next=applyAction(s,a);assert.equal(next.event.player,s.toMove);visit(next.state);}}for(const firstPlayer of [0,1])visit(createInitialState({size:1,firstPlayer}));assert.equal(leaves,48);});
test('1,000 seeded legal games preserve all invariants and deterministic replays',()=>{let draws=0;for(let seed=1;seed<=1000;seed++){const random=rng(seed),size=seed%2?4:2,firstPlayer=seed%2;let s=createInitialState({size,firstPlayer});const actions=[];while(s.toMove!==null){const legal=getLegalActions(s),action=legal[Math.floor(random()*legal.length)],before=serialize(s),next=applyAction(s,action);assert.equal(serialize(s),before);assert.equal(next.state.ply,s.ply+1);assert.ok(next.event.capturedBoxes.length<=2);assert.equal(next.state.toMove,next.event.terminal?null:next.event.capturedBoxes.length?s.toMove:1-s.toMove);s=next.state;actions.push(action);assert.deepEqual(deserialize(serialize(s)),s);}assert.equal(getScore(s).human+getScore(s).jev,size*size);if(getOutcome(s)==='draw')draws++;const result=replay({format:'jev-arcade-replay-v1',game:'dots-and-boxes',rulesVersion:RULES_VERSION,boardSize:size,firstPlayer,actions});assert.equal(serialize(result.state),serialize(s));}assert.ok(draws>0);});
test('reject invalid replay versions, excess moves and inconsistent state arrays',()=>{assert.throws(()=>replay({}));const s=createInitialState();s.boxes[0]=0;assert.throws(()=>serialize(s));assert.throws(()=>createInitialState({firstPlayer:2}));assert.throws(()=>geometry(10));});
function exactValue(s){if(s.toMove===null){const score=getScore(s);return score.jev-score.human;}const values=getLegalActions(s).map(a=>exactValue(applyAction(s,a).state));return (s.toMove===1?Math.max:Math.min)(...values);}
test('bounded solver matches independent exhaustive oracle on small endgames',()=>{for(let seed=1;seed<=20;seed++){const random=rng(seed);let s=createInitialState({size:2,firstPlayer:seed%2});while(s.edges.filter(e=>e===null).length>5){const legal=getLegalActions(s);s=applyAction(s,legal[Math.floor(random()*legal.length)]).state;}const candidates=analyzeCandidates(s,'jev',{nodes:100000,exactThreshold:12});for(const c of candidates){assert.equal(c.search.exact,true);assert.equal(c.search.estimate,exactValue(applyAction(s,{edgeId:c.edgeId}).state));}assert.ok(exactRegret(candidates,candidates[0].edgeId,s.toMove)>=0);}});
test('search budgets are hard bounded and unsolved regret remains null',()=>{const candidates=analyzeCandidates(createInitialState(),'hard',{nodes:80});assert.ok(candidates.reduce((n,c)=>n+c.search.nodes,0)<=80);assert.ok(candidates.some(c=>!c.search.exact));assert.equal(exactRegret(candidates,0,0),null);});
test('fully drawn perimeter forms a four-box loop, boundary ports stay separate',()=>{let s=createInitialState({size:2});for(const edgeId of [0,1,4,5,6,8,9,11])s=applyAction(s,{edgeId}).state;const list=components(s);assert.equal(list.length,1);assert.equal(list[0].type,'loop');assert.equal(list[0].length,4);assert.equal(list[0].exteriorPorts,0);});
test('local heuristic is deterministic',()=>{const s=createInitialState();assert.deepEqual(heuristicAction(s),heuristicAction(s));});
